apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  project: default
  source:
    repoURL: https://github.com/creed-braton/homelab.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
