---
- name: Initialize worker node
  hosts: worker
  become: yes
  tasks:
    - name: Generate kubeadm join command
      command: kubeadm token create --print-join-command
      register: join_cmd
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true

    - name: Join worker to cluster
      command: "{{ join_cmd.stdout }}"
