global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: keycloak
    metrics_path: /metrics
    static_configs:
      - targets: ["keycloak:9000"]

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: nginx
    metrics_path: /metrics
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: postgres
    metrics_path: /metrics
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: cloudflare-tunnel
    metrics_path: /metrics
    static_configs:
      - targets: ["cloudflare-tunnel:6000"]
