apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sudojo
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/creed-braton/sudojo.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: sudojo
